---
title: "Reproducible Pitch for ddp"
author: "Padmini Krishnadas"
date: "09.11.2020"
output:
  slidy_presentation: default
  html_document:
    number_sections: yes
    toc: yes
  ioslides_presentation: default
mode: selfcontained
job: Reproducible Pitch Presentation
subtitle: Dependence of mpg on variables
highlighter: highlight.js
widgets: bootstrap
---

## Coursera Reproducible Pitch

- Find here all the data that have been use for this presentation and also for the first part of the data Science Project: "First, you will create a Shiny application and deploy it on Rstudio's servers.Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application."

## mtcars Dataset

### Motor Trend Car Road Tests

> The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of design and performance for 32 differnt automobiles.
### Source:
> Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.
```{r}
library(datasets)
head(mtcars, 3)
```
---

## Dataset used- mtcars.

Format:
**the data frame has 32 observations on 11 different variables.**

| INDEX | FIELD |       DETIAL          |
| ----- | ----- | --------------------- |
| 1     | mpg   | Miles/(US) gallon     |
| 2     | cyl   | Number of cylinders   |
| 3    	| disp  | Displacement (cu.in.) |
| 4   	| hp    | Gross horsepower      |
| 5   	| drat  | Rear axle ratio       |
| 6    	| wt    | Weight (lb/1000)      |
| 7    	| qsec  | 1/4 mile time         |
| 8    	| vs    | V/S                   |
| 9   	| am    | Transmission          |
| 10   	| gear  | Number of forward gear|
| 11  	| carb  | Number of carburetors |

---

## Analysing the Main Code

```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=Data)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(Data, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })
```